version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
#      - "80:80/tcp"
      - target: 80 # docker port
        published: 8080 # published port
        protocol: tcp # tpc/udp # Optional, only select one tcp or udp, by default it will choose tcp
        # mode: host # Optional
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Madrid'
      DNS1: '8.8.8.8'
      DNS2: '8.8.4.4'
#     # WEBPASSWORD: 'set a secure password here or it will be random'
#       WEBPASSWORD: 'a'
    # Volumes store your data between container upgrades
    volumes:
      - ./etc-pihole:/etc/pihole/
      - ./etc-dnsmasq.d:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
