version: "3.9"
services:
  sdk:
    image: "budtmo/docker-android-x86-8.1"
#    name: "android-container"
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/:rw
    privileged: true
#    network_mode: host
    ports:
      - target: 6080
        published: 6080
        mode: host
      - target: 5555
        published: 5555
        mode: host

    environment: 
      - DEVICE=Samsung Galaxy S6
