version: '3'

networks:
  my-network:
    driver: bridge
services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '389:1389'
      - '636:1636'
#      - '1389:1389'
#      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      - my-network
    volumes:
      - 'openldap_data:/bitnami/openldap'
#  myapp:
#    image: 'YOUR_APPLICATION_IMAGE'
  phpldap:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - 443:443
#    depends_on:
#      - slapd
    links:
      - openldap:openldap
    hostname: phpldap

    networks:
      - my-network
volumes:
  openldap_data:
    driver: local
