# https://hub.docker.com/r/bitnami/openldap//
version: '3'

services:
  openldap:
    image: docker.io/bitnami/openldap:2-debian-10
    ports:
      - '1389:1389'
      - '1636:1636'
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
    tty: true
    stdin_open: true
    domainname: "example.org" # important: same as hostname
    hostname: "example.org"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap
    links:
      - openldap

volumes:
  openldap_data:
    driver: local
